name = "weightchallenge"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[vars]
FROM_EMAIL = "Big Boss Weight Challenge <noreply@yourdomain.com>"

[assets]
directory = "./frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "weight-challenge-db"
database_id = "ef728569-8b5e-494d-b0c1-f75c4455548d"
